using CoreKernel.Messaging.Events;
using FluentAssertions;
using MediatR;

namespace CoreKernel.Messaging.Tests;

/// <summary>
/// Contains unit tests for the event interfaces <see cref="IEvent"/>, <see cref="IDomainEvent"/>,
/// <see cref="IEventHandler{TEvent}"/>, and <see cref="IDomainEventHandler{TEvent}"/>.
/// These tests verify that the interfaces correctly extend MediatR's notification interfaces.
/// </summary>
public class EventTests
{
    #region Test Events

    /// <summary>
    /// A test event implementation.
    /// </summary>
    private class OrderCreatedEvent : IEvent
    {
        public Guid Id { get; init; }
        public DateTime TimeStamp { get; init; }
        public Guid CorrelationId { get; init; }
        
        public Guid OrderId { get; }
        public string CustomerName { get; }

        public OrderCreatedEvent(Guid orderId, string customerName, Guid? correlationId = null)
        {
            Id = Guid.NewGuid();
            TimeStamp = DateTime.UtcNow;
            CorrelationId = correlationId ?? Guid.NewGuid();
            OrderId = orderId;
            CustomerName = customerName;
        }
    }

    /// <summary>
    /// A test domain event implementation.
    /// </summary>
    private class UserRegisteredDomainEvent : IDomainEvent
    {
        public Guid Id { get; init; }
        public DateTime TimeStamp { get; init; }
        public Guid CorrelationId { get; init; }
        
        public Guid UserId { get; }
        public string Email { get; }

        public UserRegisteredDomainEvent(Guid userId, string email, Guid? correlationId = null)
        {
            Id = Guid.NewGuid();
            TimeStamp = DateTime.UtcNow;
            CorrelationId = correlationId ?? Guid.NewGuid();
            UserId = userId;
            Email = email;
        }
    }

    /// <summary>
    /// Another test domain event for testing multiple event types.
    /// </summary>
    private class OrderShippedDomainEvent : IDomainEvent
    {
        public Guid Id { get; init; }
        public DateTime TimeStamp { get; init; }
        public Guid CorrelationId { get; init; }
        
        public Guid OrderId { get; }
        public string TrackingNumber { get; }

        public OrderShippedDomainEvent(Guid orderId, string trackingNumber)
        {
            Id = Guid.NewGuid();
            TimeStamp = DateTime.UtcNow;
            CorrelationId = Guid.NewGuid();
            OrderId = orderId;
            TrackingNumber = trackingNumber;
        }
    }

    #endregion

    #region IEvent Tests

    /// <summary>
    /// Verifies that <see cref="IEvent"/> implements <see cref="INotification"/>.
    /// </summary>
    [Fact]
    public void IEvent_Should_ImplementINotification()
    {
        // Assert
        typeof(IEvent).Should().BeAssignableTo<INotification>();
    }

    /// <summary>
    /// Verifies that a custom event implementing <see cref="IEvent"/> is assignable to the interface.
    /// </summary>
    [Fact]
    public void CustomEvent_Should_ImplementIEvent()
    {
        // Arrange
        var @event = new OrderCreatedEvent(Guid.NewGuid(), "John Doe");

        // Assert
        @event.Should().BeAssignableTo<IEvent>();
        @event.Should().BeAssignableTo<INotification>();
    }

    /// <summary>
    /// Verifies that <see cref="IEvent.Id"/> property returns a valid GUID.
    /// </summary>
    [Fact]
    public void Event_Id_Should_BeGenerated()
    {
        // Arrange
        var @event = new OrderCreatedEvent(Guid.NewGuid(), "Test Customer");

        // Assert
        @event.Id.Should().NotBe(Guid.Empty);
    }

    /// <summary>
    /// Verifies that <see cref="IEvent.TimeStamp"/> property returns the event creation time.
    /// </summary>
    [Fact]
    public void Event_TimeStamp_Should_BeSet()
    {
        // Arrange
        var before = DateTime.UtcNow;
        var @event = new OrderCreatedEvent(Guid.NewGuid(), "Test Customer");
        var after = DateTime.UtcNow;

        // Assert
        @event.TimeStamp.Should().BeOnOrAfter(before);
        @event.TimeStamp.Should().BeOnOrBefore(after);
    }

    /// <summary>
    /// Verifies that <see cref="IEvent.CorrelationId"/> can be set for distributed tracing.
    /// </summary>
    [Fact]
    public void Event_CorrelationId_Should_BeSetWhenProvided()
    {
        // Arrange
        var correlationId = Guid.NewGuid();

        // Act
        var @event = new OrderCreatedEvent(Guid.NewGuid(), "Test Customer", correlationId);

        // Assert
        @event.CorrelationId.Should().Be(correlationId);
    }

    /// <summary>
    /// Verifies that <see cref="IEvent.CorrelationId"/> is auto-generated when not provided.
    /// </summary>
    [Fact]
    public void Event_CorrelationId_Should_BeAutoGenerated()
    {
        // Arrange
        var @event = new OrderCreatedEvent(Guid.NewGuid(), "Test Customer");

        // Assert
        @event.CorrelationId.Should().NotBe(Guid.Empty);
    }

    /// <summary>
    /// Verifies that event custom properties are stored correctly.
    /// </summary>
    [Fact]
    public void Event_Should_StoreCustomProperties()
    {
        // Arrange
        var orderId = Guid.NewGuid();
        var customerName = "Jane Smith";

        // Act
        var @event = new OrderCreatedEvent(orderId, customerName);

        // Assert
        @event.OrderId.Should().Be(orderId);
        @event.CustomerName.Should().Be(customerName);
    }

    #endregion

    #region IDomainEvent Tests

    /// <summary>
    /// Verifies that <see cref="IDomainEvent"/> implements <see cref="IEvent"/>.
    /// </summary>
    [Fact]
    public void IDomainEvent_Should_ImplementIEvent()
    {
        // Assert
        typeof(IDomainEvent).Should().BeAssignableTo<IEvent>();
    }

    /// <summary>
    /// Verifies that <see cref="IDomainEvent"/> implements the primitives <see cref="CoreKernel.Primitives.Abstractions.IDomainEvent"/>.
    /// </summary>
    [Fact]
    public void IDomainEvent_Should_ImplementPrimitivesIDomainEvent()
    {
        // Assert
        typeof(IDomainEvent).Should().BeAssignableTo<CoreKernel.Primitives.Abstractions.IDomainEvent>();
    }

    /// <summary>
    /// Verifies that a custom domain event implementing <see cref="IDomainEvent"/> is assignable to all expected interfaces.
    /// </summary>
    [Fact]
    public void CustomDomainEvent_Should_ImplementAllInterfaces()
    {
        // Arrange
        var @event = new UserRegisteredDomainEvent(Guid.NewGuid(), "user@example.com");

        // Assert
        @event.Should().BeAssignableTo<IDomainEvent>();
        @event.Should().BeAssignableTo<IEvent>();
        @event.Should().BeAssignableTo<INotification>();
        @event.Should().BeAssignableTo<CoreKernel.Primitives.Abstractions.IDomainEvent>();
    }

    /// <summary>
    /// Verifies that domain event has all required properties from <see cref="IEvent"/>.
    /// </summary>
    [Fact]
    public void DomainEvent_Should_HaveAllEventProperties()
    {
        // Arrange
        var correlationId = Guid.NewGuid();

        // Act
        var @event = new UserRegisteredDomainEvent(Guid.NewGuid(), "test@example.com", correlationId);

        // Assert
        @event.Id.Should().NotBe(Guid.Empty);
        @event.TimeStamp.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(1));
        @event.CorrelationId.Should().Be(correlationId);
    }

    /// <summary>
    /// Verifies that domain event custom properties are stored correctly.
    /// </summary>
    [Fact]
    public void DomainEvent_Should_StoreCustomProperties()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var email = "newuser@example.com";

        // Act
        var @event = new UserRegisteredDomainEvent(userId, email);

        // Assert
        @event.UserId.Should().Be(userId);
        @event.Email.Should().Be(email);
    }

    #endregion

    #region IEventHandler Tests

    /// <summary>
    /// Verifies that <see cref="IEventHandler{TEvent}"/> implements <see cref="INotificationHandler{TNotification}"/>.
    /// </summary>
    [Fact]
    public void IEventHandler_Should_ImplementINotificationHandler()
    {
        // Assert
        typeof(IEventHandler<OrderCreatedEvent>).Should().BeAssignableTo<INotificationHandler<OrderCreatedEvent>>();
    }

    /// <summary>
    /// Verifies that <see cref="IEventHandler{TEvent}"/> only accepts types implementing <see cref="IEvent"/>.
    /// </summary>
    [Fact]
    public void IEventHandler_GenericConstraint_Should_RequireIEvent()
    {
        // This test verifies at compile-time via the constraint on IEventHandler<TEvent>
        // where TEvent : IEvent

        // We verify by checking that the interface can be used with IEvent implementing types
        typeof(IEventHandler<OrderCreatedEvent>).Should().NotBeNull();
        typeof(IEventHandler<UserRegisteredDomainEvent>).Should().NotBeNull();
    }

    #endregion

    #region IDomainEventHandler Tests

    /// <summary>
    /// Verifies that <see cref="IDomainEventHandler{TEvent}"/> implements <see cref="IEventHandler{TEvent}"/>.
    /// </summary>
    [Fact]
    public void IDomainEventHandler_Should_ImplementIEventHandler()
    {
        // Assert
        typeof(IDomainEventHandler<UserRegisteredDomainEvent>).Should().BeAssignableTo<IEventHandler<UserRegisteredDomainEvent>>();
    }

    /// <summary>
    /// Verifies that <see cref="IDomainEventHandler{TEvent}"/> only accepts types implementing <see cref="IDomainEvent"/>.
    /// </summary>
    [Fact]
    public void IDomainEventHandler_GenericConstraint_Should_RequireIDomainEvent()
    {
        // This test verifies at compile-time via the constraint on IDomainEventHandler<TEvent>
        // where TEvent : IDomainEvent

        // We verify by checking that the interface can be used with IDomainEvent implementing types
        typeof(IDomainEventHandler<UserRegisteredDomainEvent>).Should().NotBeNull();
        typeof(IDomainEventHandler<OrderShippedDomainEvent>).Should().NotBeNull();
    }

    #endregion

    #region Event Uniqueness Tests

    /// <summary>
    /// Verifies that each event instance gets a unique ID.
    /// </summary>
    [Fact]
    public void Events_Should_HaveUniqueIds()
    {
        // Arrange
        var event1 = new OrderCreatedEvent(Guid.NewGuid(), "Customer 1");
        var event2 = new OrderCreatedEvent(Guid.NewGuid(), "Customer 2");

        // Assert
        event1.Id.Should().NotBe(event2.Id);
    }

    /// <summary>
    /// Verifies that events created at different times have different timestamps.
    /// </summary>
    [Fact]
    public async Task Events_Should_HaveDifferentTimestamps_WhenCreatedSequentially()
    {
        // Arrange
        var event1 = new OrderCreatedEvent(Guid.NewGuid(), "Customer 1");
        await Task.Delay(10); // Small delay to ensure different timestamps
        var event2 = new OrderCreatedEvent(Guid.NewGuid(), "Customer 2");

        // Assert
        event2.TimeStamp.Should().BeAfter(event1.TimeStamp);
    }

    /// <summary>
    /// Verifies that IEvent interface properties have init-only setters.
    /// </summary>
    [Fact]
    public void IEvent_Properties_Should_HaveInitSetters()
    {
        // Verify the interface has init-only properties for immutability
        var idProperty = typeof(IEvent).GetProperty(nameof(IEvent.Id));
        var timeStampProperty = typeof(IEvent).GetProperty(nameof(IEvent.TimeStamp));
        var correlationIdProperty = typeof(IEvent).GetProperty(nameof(IEvent.CorrelationId));

        idProperty.Should().NotBeNull();
        timeStampProperty.Should().NotBeNull();
        correlationIdProperty.Should().NotBeNull();

        // Verify property types
        idProperty!.PropertyType.Should().Be(typeof(Guid));
        timeStampProperty!.PropertyType.Should().Be(typeof(DateTime));
        correlationIdProperty!.PropertyType.Should().Be(typeof(Guid));
    }

    #endregion
}
